<?php
/**
 * @file
 * TK Labels Badges
 */

/**
 * Implements hook_menu().
 */
function islandora_tk_labels_menu() {
  return array(
    'admin/islandora/tools/badges/tk_labels' => array(
      'title' => 'TK Labels',
      'description' => 'Configure TK Labels settings.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_tk_labels_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_tk_labels_block_info() {
  return array(
    'islandora_tk_labels_badge' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora TK Labels Badge'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_tk_labels_block_view($delta = '') {
  module_load_include('inc', 'islandora_badges', 'includes/utilities');
  module_load_include('inc', 'islandora_tk_labels', 'includes/utilities');
  $to_render = array();

  if ($delta == 'islandora_tk_labels_badge') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      // Check CModel against Badges configuration.
      if (islandora_badges_show_for_cmodel($object)) {
        $project_id = islandora_tk_labels_get_uri($object);
        if (!isset($project_id)) { 
          return;
        }
        $badge = islandora_tk_labels_get_html($project_id);
        $to_render['content'] = $badge;
      }
    }
  }
  return $to_render;
}
